support raw request body matching
- added test case for xml request body
- fix error in util.js due to missing object prototype on ubuntu
- url param objects have (for whatever reason) no object prototype
- calling source.hasOwnProperty results in error: source.hasOwnProperty is not a function
- safe version: Object.hasOwnProperty.call
- fix test failure on ubuntu: error message longer than expected (check for substring instead)